[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
ast = true
extra_output = ["abi", "evm.bytecode"]
extra_output_files = ["abi"]

# Testing
verbosity = 2
fuzz = { runs = 256, max_test_rejects = 65536 }
invariant = { runs = 256, depth = 15 }

# Formatter
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "preserve"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
